import RNHTMLtoPDF from 'react-native-html-to-pdf';
import RNFS from 'react-native-fs';
import Share from 'react-native-share';
import * as XLSX from 'xlsx';

import type {ReportSummary, ReportTxn} from './entities';
import {formatINR} from '@utils/currency';
import {formatDisplayDate} from '@utils/date';

function fileStem(summary: ReportSummary): string {
  return `SmartCashBook_Report_${summary.from}_to_${summary.to}`;
}

function categoryRows(rows: ReportSummary['incomeByCategory']): string {
  if (rows.length === 0) {
    return '<tr><td colspan="3" class="muted">No entries</td></tr>';
  }
  return rows
    .map(
      r => `<tr>
        <td>${escapeHtml(r.category)}</td>
        <td class="num">${formatINR(r.amount)}</td>
        <td class="num">${Math.round(r.share * 100)}%</td>
      </tr>`,
    )
    .join('');
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function transactionRowsHtml(txns: ReportTxn[]): string {
  if (txns.length === 0) {
    return '<tr><td colspan="5" class="muted">No transactions in this range</td></tr>';
  }
  return txns
    .map(
      t => `<tr>
        <td>${formatDisplayDate(t.date)}</td>
        <td>${t.type === 'income' ? 'Income' : 'Expense'}</td>
        <td>${escapeHtml(t.category)}${t.party ? ` · ${escapeHtml(t.party)}` : ''}</td>
        <td class="num" style="color:${t.type === 'income' ? '#16A34A' : '#DC2626'}">${
          t.type === 'income' ? '+' : '−'
        }${formatINR(t.amount)}</td>
        <td>${escapeHtml(t.notes)}</td>
      </tr>`,
    )
    .join('');
}

/** Build a clean, printable HTML document for the report PDF. */
export function buildReportHtml(
  summary: ReportSummary,
  businessName: string,
  txns: ReportTxn[] = [],
): string {
  const profitColor = summary.profit >= 0 ? '#16A34A' : '#DC2626';
  return `<!doctype html><html><head><meta charset="utf-8" />
  <style>
    * { font-family: -apple-system, Roboto, Arial, sans-serif; color: #0F172A; }
    body { padding: 28px; }
    h1 { font-size: 20px; margin: 0; }
    .sub { color: #64748B; font-size: 12px; margin-top: 2px; }
    .cards { display: flex; gap: 12px; margin: 20px 0; }
    .card { flex: 1; border: 1px solid #E2E8F0; border-radius: 12px; padding: 12px; }
    .card .label { font-size: 11px; color: #64748B; text-transform: uppercase; }
    .card .value { font-size: 18px; font-weight: 700; margin-top: 4px; }
    h2 { font-size: 14px; margin: 22px 0 8px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th, td { text-align: left; padding: 8px; border-bottom: 1px solid #E2E8F0; }
    th { color: #64748B; font-weight: 600; }
    .num { text-align: right; }
    .muted { color: #94A3B8; text-align: center; }
    .foot { margin-top: 24px; color: #94A3B8; font-size: 10px; }
  </style></head><body>
    <h1>${escapeHtml(businessName)}</h1>
    <div class="sub">Profit &amp; Loss · ${formatDisplayDate(summary.from)} – ${formatDisplayDate(summary.to)}</div>
    <div class="cards">
      <div class="card"><div class="label">Income</div><div class="value" style="color:#16A34A">${formatINR(summary.incomeTotal)}</div></div>
      <div class="card"><div class="label">Expense</div><div class="value" style="color:#DC2626">${formatINR(summary.expenseTotal)}</div></div>
      <div class="card"><div class="label">Net profit</div><div class="value" style="color:${profitColor}">${formatINR(summary.profit)}</div></div>
    </div>
    <h2>Income by category</h2>
    <table><tr><th>Category</th><th class="num">Amount</th><th class="num">Share</th></tr>${categoryRows(summary.incomeByCategory)}</table>
    <h2>Expense by category</h2>
    <table><tr><th>Category</th><th class="num">Amount</th><th class="num">Share</th></tr>${categoryRows(summary.expenseByCategory)}</table>
    <h2>Transactions (${txns.length})</h2>
    <table><tr><th>Date</th><th>Type</th><th>Category · Party</th><th class="num">Amount</th><th>Notes</th></tr>${transactionRowsHtml(txns)}</table>
    <div class="foot">Generated by Smart CashBook${summary.source === 'local' ? ' · offline figures from this device' : ''}</div>
  </body></html>`;
}

/** Build a spreadsheet-friendly CSV of the report. */
export function buildReportCsv(summary: ReportSummary): string {
  const lines: string[] = [];
  lines.push(`Report,Profit & Loss`);
  lines.push(`From,${summary.from}`);
  lines.push(`To,${summary.to}`);
  lines.push('');
  lines.push('Metric,Amount');
  lines.push(`Income total,${summary.incomeTotal}`);
  lines.push(`Expense total,${summary.expenseTotal}`);
  lines.push(`Net profit,${summary.profit}`);
  lines.push('');
  lines.push('Income category,Amount,Share %');
  for (const r of summary.incomeByCategory) {
    lines.push(`${csv(r.category)},${r.amount},${Math.round(r.share * 100)}`);
  }
  lines.push('');
  lines.push('Expense category,Amount,Share %');
  for (const r of summary.expenseByCategory) {
    lines.push(`${csv(r.category)},${r.amount},${Math.round(r.share * 100)}`);
  }
  return lines.join('\n');
}

function csv(value: string): string {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

// --- Excel (.xlsx) ----------------------------------------------------------

/** Rows for the "P&L Summary" sheet (numbers kept numeric for Excel maths). */
export function summaryAoa(summary: ReportSummary): (string | number)[][] {
  const rows: (string | number)[][] = [
    ['Smart CashBook — Profit & Loss'],
    ['Period', `${summary.from} to ${summary.to}`],
    [summary.source === 'local' ? 'Source' : '', summary.source === 'local' ? 'Offline (this device)' : ''],
    [],
    ['Metric', 'Amount (₹)'],
    ['Income total', summary.incomeTotal],
    ['Expense total', summary.expenseTotal],
    ['Net profit', summary.profit],
    [],
    ['Income by category', 'Amount (₹)', 'Share %'],
    ...summary.incomeByCategory.map(r => [r.category, r.amount, Math.round(r.share * 100)]),
    [],
    ['Expense by category', 'Amount (₹)', 'Share %'],
    ...summary.expenseByCategory.map(r => [r.category, r.amount, Math.round(r.share * 100)]),
  ];
  return rows;
}

/** Rows for the "Transactions" sheet — a classic ledger with debit/credit cols. */
export function transactionsAoa(txns: ReportTxn[]): (string | number)[][] {
  const header = ['Date', 'Type', 'Category', 'Vendor / Payer', 'Income (₹)', 'Expense (₹)', 'Notes'];
  const body = txns.map(t => [
    t.date,
    t.type === 'income' ? 'Income' : 'Expense',
    t.category,
    t.party,
    t.type === 'income' ? t.amount : '',
    t.type === 'expense' ? t.amount : '',
    t.notes,
  ]);
  const incomeTotal = txns.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0);
  const expenseTotal = txns.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
  const totals = ['', '', '', 'Total', incomeTotal, expenseTotal, ''];
  return [header, ...body, totals];
}

/** Build the two-sheet workbook (P&L Summary + Transactions). */
export function buildReportWorkbook(
  summary: ReportSummary,
  txns: ReportTxn[],
): XLSX.WorkBook {
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.aoa_to_sheet(summaryAoa(summary)),
    'P&L Summary',
  );
  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.aoa_to_sheet(transactionsAoa(txns)),
    'Transactions',
  );
  return wb;
}

/** Serialize the workbook to a base64 string (for RNFS to write to disk). */
export function workbookToBase64(wb: XLSX.WorkBook): string {
  return XLSX.write(wb, {type: 'base64', bookType: 'xlsx'});
}

// --- File + share entry points ---------------------------------------------

/** Render the report (P&L + full transactions) to a PDF and share it. */
export async function exportReportPdf(
  summary: ReportSummary,
  businessName: string,
  txns: ReportTxn[] = [],
): Promise<void> {
  const {filePath} = await RNHTMLtoPDF.convert({
    html: buildReportHtml(summary, businessName, txns),
    fileName: fileStem(summary),
    directory: 'Documents',
  });
  if (!filePath) throw new Error('Could not generate the PDF.');
  await Share.open({
    url: `file://${filePath}`,
    type: 'application/pdf',
    failOnCancel: false,
  });
}

/** Write a real .xlsx (P&L Summary + Transactions sheets) and share it. */
export async function exportReportXlsx(
  summary: ReportSummary,
  txns: ReportTxn[],
): Promise<void> {
  const base64 = workbookToBase64(buildReportWorkbook(summary, txns));
  const path = `${RNFS.DocumentDirectoryPath}/${fileStem(summary)}.xlsx`;
  await RNFS.writeFile(path, base64, 'base64');
  await Share.open({
    url: `file://${path}`,
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    failOnCancel: false,
  });
}

/** Write the report CSV to a file and open the share sheet (for Excel etc.). */
export async function exportReportCsv(summary: ReportSummary): Promise<void> {
  const path = `${RNFS.DocumentDirectoryPath}/${fileStem(summary)}.csv`;
  await RNFS.writeFile(path, buildReportCsv(summary), 'utf8');
  await Share.open({
    url: `file://${path}`,
    type: 'text/csv',
    failOnCancel: false,
  });
}
